import { useState } from 'react';
import { ClipboardCheck, Clock3, LockKeyhole, ShieldCheck } from 'lucide-react';
import { blockers, requirements, type State } from '../../lib/udyog';
export default function DepartmentOverview({ state }: { state: State }) {
  const [now] = useState(() => Date.now());
  const queue = requirements(state.project).filter(item => !item.advisory).map(item => ({ item, app: state.applications[item.id], blocked: blockers(state, item) }));
  const ready = state.documents.filter(doc => doc.file && doc.checked).length;
  const score = Math.round((queue.filter(row => row.app.status === 'approved').length / Math.max(1, queue.length) * 50) + (ready / Math.max(1, state.documents.length) * 50));
  return <section className="uw-panel uw-department"><div className="uw-section-heading"><div><span className="uw-eyebrow">ACCESS VIEW / DEPARTMENT WORK QUEUE</span><h2>Review readiness, not live status.</h2></div><span className="uw-source-state uw-source-reference-only"><i/>local record only</span></div><p className="uw-profile-note">This queue is derived from the current browser workspace. It does not represent a connected department system or statutory service clock.</p><div className="uw-department-score"><strong>{score}<small>/100</small></strong><span><b>Zero-defect preparation score</b><small>Documents checked and routes recorded in this workspace</small></span></div><div className="uw-department-table"><div className="uw-department-row uw-department-head"><span>Application / owner</span><span>Query age</span><span>Internal target</span><span>Blocking reason</span></div>{queue.map(({ item, app, blocked }) => { const waiting = app.status === 'query' ? 'Applicant' : app.status === 'submitted' ? item.agency : 'Not started'; const age = app.status === 'query' ? `${Math.max(1, Math.floor((now - new Date(app.messages.at(-1)?.at || now).getTime()) / 86400000))}d` : 'not started'; return <div className="uw-department-row" key={item.id}><span><b>{item.title}</b><small>{waiting} · owner: {waiting}</small></span><span><Clock3 size={13}/> {age}</span><span>Internal target: 5 working days</span><span className={blocked.length ? 'is-blocked' : 'is-ready'}>{blocked.length ? <><LockKeyhole size={13}/> {blocked[0]}</> : <><ShieldCheck size={13}/> Ready for review</>}</span></div>; })}</div><div className="uw-department-foot"><ClipboardCheck size={14}/> Inspection readiness is a preparation signal based on declared evidence, not an inspection result.</div></section>;
}
