import { FormEvent, useState } from 'react';
import { BookOpen, Bot, LoaderCircle, Send, ShieldCheck, Sparkles } from 'lucide-react';
import type { Project } from '../../lib/udyog';
import { projectToProjectData } from '../../lib/arthix-rules';
import type { RagAnswer } from '../../lib/rag-engine';
export default function RagAssistantView({ project, initialQuery = '' }: { project: Project; initialQuery?: string }) {
  const [query, setQuery] = useState(initialQuery || 'Which approvals should I verify before establishing this unit?'); const [answer, setAnswer] = useState<RagAnswer | null>(null); const [busy, setBusy] = useState(false); const [indexed, setIndexed] = useState<number | null>(null);
  async function ask(event?: FormEvent) { event?.preventDefault(); if (!query.trim()) return; setBusy(true); try { const response = await fetch('/api/rag/query', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ query, project: projectToProjectData(project) }) }); setAnswer(await response.json()); const status = await fetch('/api/rag/query'); const health = await status.json(); setIndexed(health.indexedRules); } finally { setBusy(false); } }
  return <div className="uw-rag-view"><div className="uw-info-strip"><Sparkles size={18}/><span><strong>Source-grounded retrieval only.</strong> Results are grounded in deterministic indexed rules and official links. An optional server-side LLM may only explain retrieved context and must cite allowed sources. Request and inspect citations before acting.</span></div><section className="uw-panel uw-rag-hero"><div><span className="uw-eyebrow">SOURCE-GROUNDED RETRIEVAL</span><h2>Ask the rules. See the evidence.</h2><p>Use this as research support, not a statutory determination. Authority-specific requirements and decisions remain with the responsible department.</p></div><span className="uw-rag-health"><i/>No LLM · local retrieval</span></section><section className="uw-panel uw-rag-conversation"><div className="uw-rag-context"><span><BookOpen size={15}/> {project.name}</span><span>{project.sector} · {project.district} · {project.stage}</span>{indexed !== null && <span>{indexed} indexed rules</span>}</div><form onSubmit={ask} className="uw-rag-form"><textarea value={query} onChange={event => setQuery(event.target.value)} aria-label="Compliance question" maxLength={1000} placeholder="Ask about an approval, dependency, document or timing..."/><button className="uw-button uw-primary" disabled={busy || !query.trim()}>{busy ? <LoaderCircle className="uw-spin" size={16}/> : <Send size={15}/>}Retrieve guidance</button></form>{answer ? <div className="uw-rag-answer"><div className="uw-rag-answer-head"><span className="uw-rag-bot"><Bot size={18}/></span><div><strong>Retrieved guidance</strong><small>{answer.confidence} confidence · deterministic retrieval · verify citations</small></div></div><p>{answer.answer}</p><div className="uw-rag-boundaries"><strong>Before you act</strong>{answer.boundaries.map(boundary => <span key={boundary}><ShieldCheck size={12}/>{boundary}</span>)}<span><ShieldCheck size={12}/>Ask for a citation to the current authority page or notification.</span></div></div> : <div className="uw-rag-empty"><Bot size={25}/><strong>No answer retrieved yet</strong><span>Ask a focused question and inspect the source links returned with the result.</span></div>}</section></div>;
}

