import { FormEvent, useEffect, useState } from 'react';
import { BookOpen, Bot, LoaderCircle, Send, ShieldCheck, Sparkles } from 'lucide-react';
import type { Project } from '../../lib/udyog';
import { projectToProjectData } from '../../lib/arthix-rules';
import type { RagAnswer } from '../../lib/rag-engine';
export default function RagAssistantView({ project, initialQuery = '' }: { project: Project; initialQuery?: string }) {
  const [query, setQuery] = useState(initialQuery || 'Which approvals should I verify before establishing this unit?'); const [answer, setAnswer] = useState<RagAnswer | null>(null); const [busy, setBusy] = useState(false); const [health, setHealth] = useState<{ llm: string; indexedRules: number } | null>(null);
  useEffect(() => { fetch('/api/rag/query').then(response => response.json()).then(setHealth).catch(() => undefined); }, []);
  const llmOn = Boolean(health && health.llm !== 'none');
  async function ask(event?: FormEvent) { event?.preventDefault(); if (!query.trim()) return; setBusy(true); try { const response = await fetch('/api/rag/query', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ query, project: projectToProjectData(project) }) }); setAnswer(await response.json()); const status = await fetch('/api/rag/query'); setHealth(await status.json()); } finally { setBusy(false); } }
  return <div className="uw-rag-view"><div className="uw-info-strip"><Sparkles size={18}/><span><strong>Official-source grounding.</strong> Answers are retrieved from indexed rules and live official government pages. When an LLM is connected it may only explain that retrieved material and must cite the allowed sources. Inspect every citation before acting.</span></div><section className="uw-panel uw-rag-hero"><div><span className="uw-eyebrow">SOURCE-GROUNDED RETRIEVAL</span><h2>Ask the rules. See the evidence.</h2><p>Use this as research support, not a statutory determination. Authority-specific requirements and decisions remain with the responsible department.</p></div><span className="uw-rag-health"><i/>{llmOn ? `LLM · ${health?.llm} · official web grounding` : 'No LLM · rules + official pages'}</span></section><section className="uw-panel uw-rag-conversation"><div className="uw-rag-context"><span><BookOpen size={15}/> {project.name}</span><span>{project.sector} · {project.district} · {project.stage}</span>{health && <span>{health.indexedRules} indexed rules</span>}</div><form onSubmit={ask} className="uw-rag-form"><textarea value={query} onChange={event => setQuery(event.target.value)} aria-label="Compliance question" maxLength={1000} placeholder="Ask about an approval, dependency, document or timing..."/><button className="uw-button uw-primary" disabled={busy || !query.trim()}>{busy ? <LoaderCircle className="uw-spin" size={16}/> : <Send size={15}/>}Retrieve guidance</button></form>{answer ? <div className="uw-rag-answer"><div className="uw-rag-answer-head"><span className="uw-rag-bot"><Bot size={18}/></span><div><strong>Retrieved guidance</strong><small>{answer.confidence} confidence · {answer.provider === 'deterministic' ? 'deterministic retrieval' : `${answer.provider} grounded`} · verify citations</small></div></div><p>{answer.answer}</p>{answer.citations.length > 0 && <div className="uw-rag-citations"><strong>Official sources</strong>{answer.citations.map(citation => <a key={citation.id} href={citation.url} target="_blank" rel="noreferrer"><BookOpen size={12}/><span><b>{citation.title}</b><small>{citation.authority} · {citation.version}</small></span></a>)}</div>}<div className="uw-rag-boundaries"><strong>Before you act</strong>{answer.boundaries.map(boundary => <span key={boundary}><ShieldCheck size={12}/>{boundary}</span>)}<span><ShieldCheck size={12}/>Ask for a citation to the current authority page or notification.</span></div></div> : <div className="uw-rag-empty"><Bot size={25}/><strong>No answer retrieved yet</strong><span>Ask a focused question and inspect the source links returned with the result.</span></div>}</section></div>;
}

