import React, { useState } from 'react';
import { ArrowRight, Bell, Bookmark, Building2, CalendarDays, Check, Clock3, Factory, GitBranch, Leaf, LifeBuoy, MessageSquare, Plus, Search, ShieldCheck } from 'lucide-react';
import { dateLabel, requirements, sources, today, type Application } from '../../lib/udyog';
import { Badge, Empty, Source } from './Workspace';
import type { ViewProps } from './Views';

export function serviceTimeline(app: Application, now: number, targetDays: number) {
  const messages = [...app.messages].sort((a, b) => Date.parse(a.at) - Date.parse(b.at));
  // The workflow records submission as the first message and approval as the last.
  const first = messages[0], latest = messages[messages.length - 1];
  const submittedAt = app.status !== 'draft' && first?.role === 'Applicant' ? first.at : null;
  const approvedAt = app.status === 'approved' && latest?.role === 'Department officer' ? latest.at : null;
  const waitingFor = app.status === 'query' ? 'Applicant' : app.status === 'submitted' ? 'Department' : null;
  const stageSince = waitingFor ? latest?.at || null : null;
  const elapsed = (start: string | null, end: number) => {
    const startTime = start ? Date.parse(start) : NaN;
    return Number.isFinite(startTime) && Number.isFinite(end) && startTime <= end && end <= now ? (end - startTime) / 86400000 : null;
  };
  const turnaroundDays = app.status === 'approved' ? elapsed(submittedAt, approvedAt ? Date.parse(approvedAt) : NaN) : null;
  const elapsedDays = app.status === 'approved' ? turnaroundDays : elapsed(submittedAt, now);
  const waitingDays = elapsed(stageSince, now);
  const overTarget = elapsedDays === null || !Number.isInteger(targetDays) || targetDays < 1 ? null : elapsedDays > targetDays;
  return { submittedAt, approvedAt, waitingFor, stageSince, elapsedDays, waitingDays, turnaroundDays, overTarget };
}

export default function ServiceViews({ state, role, view, update, notify, go, setSelected }: ViewProps) {
  const [inspectionApp, setInspectionApp] = useState('cte');
  const [inspectionDate, setInspectionDate] = useState('');
  const [note, setNote] = useState('');
  const [subject, setSubject] = useState('');
  const [text, setText] = useState('');
  const [replies, setReplies] = useState<Record<string, string>>({});
  const [savedOnly, setSavedOnly] = useState(false);
  const [filter, setFilter] = useState('');
  const [target, setTarget] = useState('7');
  const [timelineFilter, setTimelineFilter] = useState('all');
  const [asOf, setAsOf] = useState(() => Date.now());
  const applicant = role === 'Applicant', department = role === 'Department officer';
  const checklist = requirements(state.project);
  const approved = checklist.filter(r => !r.advisory && state.applications[r.id].status === 'approved');

  if (view === 'Service Timelines') {
    const now = asOf, targetDays = Number(target);
    const validTarget = Number.isInteger(targetDays) && targetDays >= 1 && targetDays <= 365;
    const rows = checklist.filter(r => !r.advisory).map(r => ({ ...r, status: state.applications[r.id].status, ...serviceTimeline(state.applications[r.id], now, validTarget ? targetDays : NaN) }));
    const open = rows.filter(r => r.waitingFor);
    const overdue = open.filter(r => r.overTarget === true).length;
    const within = open.filter(r => r.overTarget === false).length;
    const visible = rows.filter(r => timelineFilter === 'all' || (timelineFilter === 'overdue' ? r.waitingFor && r.overTarget === true : timelineFilter === 'within' ? r.waitingFor && r.overTarget === false : r.waitingFor === timelineFilter));
    const duration = (days: number | null) => days === null ? 'Unavailable' : days === 0 ? '0 days' : days < 0.1 ? '<0.1 days' : `${days.toFixed(1)} days`;
    const timestamp = (at: string | null) => at ? <time dateTime={at}>{dateLabel(at)}<small>{new Date(at).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</small></time> : 'Not recorded';
    return <>
      <div className="uw-info-strip"><Clock3 size={19} /><span><strong>System review target, not a statutory SLA.</strong> Elapsed time uses recorded local application messages, not live government metrics. Calendar days are elapsed 24-hour periods, including weekends. Queries do not pause or reset the overall clock; no legal clock pauses are inferred.</span></div>
      <section className="uw-panel">
        <div className="uw-section-heading uw-timeline-controls"><div><span className="uw-eyebrow">{state.project.caseId} / LOCAL RECORDS ONLY</span><h2>{applicant ? 'Your case timelines' : 'Department & facilitation overview'}</h2><p>{state.project.name}. This workspace contains one project, not a department-wide caseload.</p></div><label className="uw-field uw-timeline-target">System target (calendar days)<input type="number" min="1" max="365" step="1" value={target} aria-invalid={!validTarget} aria-describedby="uw-target-note" onChange={e => setTarget(e.target.value)} /></label></div>
        <p id="uw-target-note" className={validTarget ? 'uw-muted' : 'uw-issue'}>{validTarget ? 'Local view setting only; resets when you leave this view and is not exported. Attention compares total elapsed time against this target.' : 'Enter a whole number from 1 to 365 to classify review attention.'}</p>
        <div className="uw-stats" aria-label="Service timeline counts"><div><span className="uw-eyebrow">OPEN APPLICATIONS</span><div className="uw-stat-value">{open.length}</div><p>{open.filter(r => r.waitingFor === 'Department').length} awaiting department / {open.filter(r => r.waitingFor === 'Applicant').length} awaiting applicant</p></div><div><span className="uw-eyebrow">OVER REVIEW TARGET</span><div className="uw-stat-value uw-amber-text">{validTarget ? overdue : 'N/A'}</div><p>Open cases needing review attention</p></div><div><span className="uw-eyebrow">WITHIN REVIEW TARGET</span><div className="uw-stat-value">{validTarget ? within : 'N/A'}</div><p>{open.filter(r => r.elapsedDays === null).length} open cases without usable timing</p></div><div><span className="uw-eyebrow">APPROVALS RECORDED</span><div className="uw-stat-value">{approved.length}</div><p>Turnaround ends at the decision message</p></div></div>
        {!applicant && <div className="uw-table-scroll"><table className="uw-table"><caption className="uw-sr-only">Department waiting overview for this project</caption><thead><tr><th>Department / service agency</th><th>Awaiting department</th><th>Awaiting applicant</th><th>Open over target</th><th>Longest current wait</th></tr></thead><tbody>{[...new Set(rows.map(r => r.agency))].map(agency => {
          const pending = open.filter(r => r.agency === agency), waits = pending.flatMap(r => r.waitingDays === null ? [] : [r.waitingDays]);
          return <tr key={agency}><td><strong>{agency}</strong></td><td>{pending.filter(r => r.waitingFor === 'Department').length}</td><td>{pending.filter(r => r.waitingFor === 'Applicant').length}</td><td>{validTarget ? pending.filter(r => r.overTarget === true).length : 'N/A'}</td><td>{waits.length ? duration(Math.max(...waits)) : pending.length ? 'Unavailable' : 'No open cases'}</td></tr>;
        })}</tbody></table></div>}
        <div className="uw-panel-footnote"><Clock3 size={14} /><span>Calculated {new Date(now).toLocaleString('en-IN')}. Refresh to recalculate elapsed time.</span><button className="uw-text-button" onClick={() => setAsOf(Date.now())}>Refresh timings</button></div>
      </section>
      <section className="uw-panel uw-spaced"><div className="uw-section-heading"><div><h2>Application timeline register</h2><p>Current wait starts at the latest message. Overall elapsed time starts at first submission.</p></div><label className="uw-field uw-timeline-target">Show applications<select value={timelineFilter} onChange={e => setTimelineFilter(e.target.value)}><option value="all">All applications ({rows.length})</option><option value="overdue">Open over target</option><option value="within">Open within target</option><option value="Department">Awaiting department</option><option value="Applicant">Awaiting applicant</option></select></label></div>
        <div className="uw-table-scroll"><table className="uw-table uw-timeline-table"><caption className="uw-sr-only">Application submission, current wait and approval turnaround</caption><thead><tr><th>Application</th><th>First submitted</th><th>Current stage / waiting since</th><th>Elapsed / turnaround</th><th>Review attention</th></tr></thead><tbody>{visible.map(r => <tr key={r.id}><td><button className="uw-text-button" onClick={() => { setSelected(r.id); go('Applications'); }}>{r.title}<ArrowRight size={12} /></button><small>{r.agency}</small><Badge status={r.status} /></td><td>{r.status === 'draft' ? 'Not submitted' : timestamp(r.submittedAt)}</td><td>{r.waitingFor ? <><strong>Awaiting {r.waitingFor.toLowerCase()}</strong><small>Since {timestamp(r.stageSince)}</small><small>Current wait: {duration(r.waitingDays)}</small></> : r.status === 'approved' ? <>System approved<small>{timestamp(r.approvedAt)}</small></> : 'Preparation; clock not started'}</td><td>{r.status === 'draft' ? 'Not started' : <><strong>{duration(r.elapsedDays)}</strong><small>{r.status === 'approved' ? 'Submission to approval' : 'Since first submission; no pauses'}</small></>}</td><td><Badge status={r.status === 'draft' || r.overTarget === null ? 'guidance' : r.overTarget ? 'query' : 'submitted'}>{r.status === 'draft' ? 'Not assessed' : r.overTarget === null ? 'Not assessable' : r.status === 'approved' ? r.overTarget ? 'Approved beyond target' : 'Approved within target' : r.overTarget ? 'Overdue vs system target' : 'Within system target'}</Badge>{r.waitingFor && r.overTarget && <small>Review with {r.waitingFor.toLowerCase()}; not an SLA breach finding.</small>}</td></tr>)}</tbody></table></div>
        {!visible.length && <Empty icon={<Clock3 size={28} />} title="No applications in this group">Change the filter or record application activity. No timing data is invented.</Empty>}
        {!rows.some(r => r.status !== 'draft') && <p className="uw-muted uw-spaced">No submissions recorded yet. Submit an application in the system to start its timeline.</p>}
      </section>
    </>;
  }

  if (view === 'Inspections') return <>
    <div className="uw-info-strip"><CalendarDays size={19} /><span><strong>Local scheduling exercise.</strong> No government visit is booked. Request a future date after a consent application is submitted. An officer can confirm, then simulate completion, including a future visit for this system. This is not proof of inspection.</span></div>
    <section className="uw-panel"><div className="uw-section-heading"><div><h2>Request a site inspection</h2><p>Choose an application in review or approved in system.</p></div><CalendarDays size={22} /></div><form className="uw-inline-form" onSubmit={e => {
      e.preventDefault(); const app = state.applications[inspectionApp];
      if (!applicant || !app || !['submitted', 'approved'].includes(app.status) || inspectionDate <= today() || state.inspections.some(i => i.app === inspectionApp && i.status !== 'completed')) { notify('Select a submitted or approved consent application, a future date, and resolve any existing open visit first.'); return; }
      update(`${inspectionApp.toUpperCase()}: inspection requested for ${dateLabel(inspectionDate)}.`, n => { n.inspections.push({ id: crypto.randomUUID(), app: inspectionApp, date: inspectionDate, status: 'requested', note: note.trim() }); }); setInspectionDate(''); setNote('');
    }}><label className="uw-field">Consent application<select value={inspectionApp} onChange={e => setInspectionApp(e.target.value)} disabled={!applicant}><option value="cte">Consent to Establish</option><option value="cto">Consent to Operate</option></select></label><label className="uw-field">Preferred future date<input type="date" required min={today(1)} value={inspectionDate} onChange={e => setInspectionDate(e.target.value)} disabled={!applicant} /></label><label className="uw-field uw-grow">Site coordination note<input value={note} maxLength={500} onChange={e => setNote(e.target.value)} placeholder="Access instructions (optional)" disabled={!applicant} /></label><button className="uw-button uw-primary" disabled={!applicant || !checklist.some(r => r.id === 'cte')}><Plus size={15} />Request visit</button></form>{!checklist.some(r => r.id === 'cte') && <p className="uw-muted uw-spaced">No consent route is included for this profile. No system consent inspection is applicable.</p>}</section>
    <section className="uw-panel uw-spaced"><div className="uw-section-heading"><h2>Inspection register</h2><Badge status="guidance">{state.inspections.length} visits</Badge></div>{state.inspections.length ? <div className="uw-table-scroll"><table className="uw-table"><thead><tr><th>Application</th><th>Requested date</th><th>Coordination note</th><th>Status</th><th>Department action</th></tr></thead><tbody>{state.inspections.map(i => <tr key={i.id}><td><strong>{i.app.toUpperCase()}</strong><small>{state.project.caseId}</small></td><td>{dateLabel(i.date)}</td><td>{i.note || 'No note provided'}</td><td><Badge status={i.status} /></td><td>{department && i.status !== 'completed' ? <button className="uw-button" disabled={i.status === 'requested' && i.date <= today()} onClick={() => { if (i.status === 'requested' && i.date <= today()) return; update(`${i.app.toUpperCase()}: inspection ${i.status === 'requested' ? 'confirmed' : 'completion simulated; site visit scheduling automated'}.`, n => { n.inspections.find(item => item.id === i.id)!.status = i.status === 'requested' ? 'confirmed' : 'completed'; }); }}>{i.status === 'requested' ? 'Confirm visit' : 'Simulate completion'}</button> : <span className="uw-muted">{i.status === 'completed' ? 'System visit completed' : 'Awaiting department officer'}</span>}{i.status === 'requested' && i.date <= today() && <><small className="uw-issue">Date passed. Request a new date.</small>{applicant && <button className="uw-text-button" onClick={() => update(`${i.app.toUpperCase()}: expired inspection request removed for rescheduling.`, n => { n.inspections = n.inspections.filter(item => item.id !== i.id); })}>Remove expired request</button>}</>}</td></tr>)}</tbody></table></div> : <Empty icon={<CalendarDays size={30} />} title="No visits requested yet">Submit a consent application in the system, then request a future date here.</Empty>}</section>
  </>;

  if (view === 'Compliance') return <>
    <div className="uw-info-strip"><Bell size={19} /><span><strong>Reminders begin after approval.</strong> No expiry periods are assumed. Enter a date from an actual consent condition for your own reference. Reminders are local only; no emails or SMS are sent.</span></div><section className="uw-panel"><div className="uw-section-heading"><div><h2>Post-approval register</h2><p>Only approved system applications appear here.</p></div><ShieldCheck size={22} /></div>{approved.length ? <div className="uw-compliance-list">{approved.map(r => {
      const a = state.applications[r.id];
      const days = a.reminder ? Math.ceil((new Date(`${a.reminder}T12:00:00`).getTime() - new Date(`${today()}T12:00:00`).getTime()) / 86400000) : null;
      return <div key={r.id}><div><Badge status="approved">System approved</Badge><h3>{r.title}</h3><p>{r.id === 'udyam' ? 'Udyam registration has no renewal requirement. Keep enterprise details current on the official portal.' : 'Check validity and conditions in the actual consent. This date is user-entered and is not an authority-issued deadline.'}</p><Source href={r.source}>Official guidance</Source></div>{r.id === 'udyam' ? <Badge status="guidance">No renewal required</Badge> : <div className="uw-renewal"><label className="uw-field">Your renewal reminder date<input type="date" aria-label={`${r.short} renewal reminder date`} disabled={!applicant} value={a.reminder || ''} onChange={e => { const value = e.target.value; update(`${r.short}: personal renewal reminder ${value ? `set to ${value}` : 'cleared'}.`, n => { n.applications[r.id].reminder = value; }); }} /></label>{days !== null ? <Badge status={days <= 30 ? 'query' : 'approved'}>{days < 0 ? `${Math.abs(days)} days overdue` : days === 0 ? 'Reminder today' : `In ${days} days`}</Badge> : <span className="uw-muted">No date set. No statutory deadline inferred.</span>}</div>}</div>;
    })}</div> : <Empty icon={<ShieldCheck size={32} />} title="Your post-approval register starts here">After an officer records a system approval, relevant follow-up guidance and reminder controls will appear.</Empty>}</section>
  </>;

  if (view === 'Government Support') {
    const resources = [
      { id: 'myscheme', title: 'Business & entrepreneurship scheme discovery', agency: 'myScheme / Government of India', why: `${state.project.sector} enterprises can explore official scheme filters. Financial and applicant details are still needed to assess any scheme.`, href: sources.schemes, tag: 'SCHEME DISCOVERY', icon: Leaf },
      { id: 'maitri', title: 'Maharashtra investor facilitation', agency: 'MAITRI / Government of Maharashtra', why: `Your project is based in ${state.project.district}, Maharashtra. MAITRI is an official starting point for state investor services and facilitation.`, href: sources.maitri, tag: 'STATE FACILITATION', icon: Building2 },
      { id: 'udyam', title: 'Explore MSME registration', agency: 'Ministry of MSME', why: 'Enterprise registration may be relevant. Check official investment and turnover criteria; this profile alone cannot determine MSME status.', href: sources.udyam, tag: 'ENTERPRISE REGISTRATION', icon: Factory },
      { id: 'nsws', title: 'Know Your Approvals', agency: 'National Single Window System', why: `${state.project.stage} stage: use the official questionnaire to discover central and state approval requirements for your proposed activity.`, href: sources.nsws, tag: 'APPROVAL DISCOVERY', icon: GitBranch },
    ];
    return <><div className="uw-info-strip"><Leaf size={19} /><span><strong>Official matching, not an eligibility decision.</strong> Matching uses declared details only. No entitlement, funding amount or approval is promised. Check current terms on the official service.</span></div><section className="uw-panel"><div className="uw-section-heading"><div><h2>A starting point for your enterprise</h2><p>Based on {state.project.sector.toLowerCase()} in {state.project.district}, with {state.project.workforce} team members.</p></div><button className={`uw-button ${savedOnly ? 'uw-primary' : ''}`} aria-pressed={savedOnly} onClick={() => setSavedOnly(!savedOnly)}><Bookmark size={15} />{savedOnly ? 'Show all resources' : `Saved (${state.saved.length})`}</button></div><div className="uw-scheme-list">{resources.filter(s => !savedOnly || state.saved.includes(s.id)).map(s => <article key={s.id}><span className="uw-scheme-icon"><s.icon size={24} /></span><div><span className="uw-eyebrow">{s.tag}</span><h3>{s.title}</h3><small>{s.agency}</small><p><strong>Why shown:</strong> {s.why}</p><Source href={s.href}>Explore official resource</Source></div><button className={`uw-icon-button uw-save ${state.saved.includes(s.id) ? 'is-saved' : ''}`} aria-label={`${state.saved.includes(s.id) ? 'Unsave' : 'Save'} ${s.title}`} aria-pressed={state.saved.includes(s.id)} onClick={() => update(`${s.title}: ${state.saved.includes(s.id) ? 'removed from' : 'added to'} saved resources.`, n => { n.saved = n.saved.includes(s.id) ? n.saved.filter(id => id !== s.id) : [...n.saved, s.id]; })}><Bookmark size={19} fill={state.saved.includes(s.id) ? 'currentColor' : 'none'} /></button></article>)}</div>{savedOnly && !state.saved.length && <Empty icon={<Bookmark size={28} />} title="Your shortlist is waiting">Switch to all resources and bookmark an official discovery link.</Empty>}</section></>;
  }

  if (view === 'Help / Grievances') return <>
    <div className="uw-help-grid"><section className="uw-panel"><div className="uw-section-heading"><div><span className="uw-eyebrow">CASE {state.project.caseId}</span><h2>Raise a project concern</h2></div><MessageSquare size={23} /></div><p className="uw-muted">This creates a local system grievance, not an official complaint. Do not enter sensitive personal information.</p><form onSubmit={e => { e.preventDefault(); if (!subject.trim() || !text.trim()) return; const id = `GR-${crypto.randomUUID().slice(0, 8).toUpperCase()}`; update(`${id}: project-linked grievance raised.`, n => { n.grievances.unshift({ id, subject: subject.trim(), text: text.trim(), status: 'Open', response: '', at: new Date().toISOString() }); }); setSubject(''); setText(''); }}><label className="uw-field">Subject<input required maxLength={120} value={subject} onChange={e => setSubject(e.target.value)} placeholder="What do you need help with?" /></label><label className="uw-field">Describe your concern<textarea required maxLength={2000} value={text} onChange={e => setText(e.target.value)} placeholder="Include the approval step and the issue you are facing." /></label><button className="uw-button uw-primary" disabled={!subject.trim() || !text.trim()}>Raise system grievance <ArrowRight size={15} /></button></form></section><section className="uw-advisory"><span className="uw-eyebrow">THE OFFICIAL ROUTE</span><h2>Need help beyond this system?</h2><p>Use MAITRI for Maharashtra investor facilitation. NSWS can help discover which approvals to investigate.</p><Source href={sources.maitri}>Visit MAITRI</Source><Source href={sources.nsws}>Visit NSWS</Source><div className="uw-advisory-note">This local conversation does not create an external ticket.</div></section></div>
    <section className="uw-panel uw-spaced"><div className="uw-section-heading"><h2>Your grievance register</h2><Badge status="guidance">{state.grievances.length} cases</Badge></div>{state.grievances.length ? <div className="uw-grievance-list">{state.grievances.map(g => <article key={g.id}><div className="uw-section-heading"><div><span className="uw-eyebrow">{g.id} / {state.project.caseId}</span><h3>{g.subject}</h3></div><Badge status={g.status} /></div><p>{g.text}</p><small className="uw-muted">Raised {dateLabel(g.at)}</small>{g.response && <div className="uw-grievance-response"><strong>Facilitation response</strong><p>{g.response}</p></div>}{role === 'Facilitation officer' && g.status !== 'Resolved' && <div className="uw-review-box">{g.status === 'Open' ? <button className="uw-button" onClick={() => update(`${g.id}: facilitation officer acknowledged grievance; in review.`, n => { n.grievances.find(item => item.id === g.id)!.status = 'In review'; })}>Acknowledge & review</button> : <><label className="uw-field">Resolution note<textarea value={replies[g.id] || ''} maxLength={2000} onChange={e => setReplies({ ...replies, [g.id]: e.target.value })} placeholder="Explain the resolution or official next step..." /></label><button className="uw-button uw-primary" disabled={!replies[g.id]?.trim()} onClick={() => update(`${g.id}: grievance resolved by facilitation officer.`, n => { const target = n.grievances.find(item => item.id === g.id)!; target.status = 'Resolved'; target.response = replies[g.id].trim(); })}>Record resolution <Check size={15} /></button></>}</div>}</article>)}</div> : <Empty icon={<LifeBuoy size={29} />} title="No open conversations yet">Raise a concern above. Its status and facilitation response stay linked to this project.</Empty>}</section>
  </>;

  return <section className="uw-panel"><div className="uw-section-heading"><div><h2>Project audit trail</h2><p>Local, editable-browser history. Not an official or tamper-proof audit record.</p></div><label className="uw-search"><Search size={16} /><input aria-label="Search activity" value={filter} onChange={e => setFilter(e.target.value)} placeholder="Search actions or roles..." /></label></div><div className="uw-full-timeline">{state.activity.filter(item => `${item.text} ${item.role}`.toLowerCase().includes(filter.toLowerCase())).map(item => <article key={item.id}><span className="uw-timeline-dot" /><time dateTime={item.at}>{dateLabel(item.at)}<small>{new Date(item.at).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</small></time><div><Badge status="guidance">{item.role}</Badge><p>{item.text}</p></div></article>)}</div>{!state.activity.some(item => `${item.text} ${item.role}`.toLowerCase().includes(filter.toLowerCase())) && <Empty icon={<Search size={26} />} title="No matching activity">Try another phrase or role.</Empty>}</section>;
}
