import { analyzeWithRulesEngine } from './rules-engine';
import { calculateOrchestration, type OrchestrationInput, type OrchestrationResult } from './dag-engine';
import type { PrevalidationState } from './prevalidation';
import type { ProjectData } from './arthix-rules';

export type AmendmentEvent = { id: string; title: string; authority: string; issuedOn: string; sourceUrl: string; summary: string; keywords: string[]; affectedRuleIds?: string[]; additionalDocuments?: string[]; dependenciesAdded?: { approvalId: string; dependsOn: string }[]; slaDays?: { approvalId: string; days: number }[] };
export type ImpactItem = { approvalId: string; title: string; impact: 'high' | 'medium' | 'low'; changes: string[]; documents: string[]; ragContext: string };
export type ChangeImpactResult = { amendment: AmendmentEvent; before: OrchestrationResult; after: OrchestrationResult; impactedApprovals: ImpactItem[]; newDocuments: string[]; prevalidationAction: string; summary: string };

export const defaultAmendments: AmendmentEvent[] = [{ id: 'gr-2026-mpcb-category', title: 'MPCB consent category and document review update', authority: 'Maharashtra Pollution Control Board', issuedOn: '2026-09-08', sourceUrl: 'https://www.mpcb.gov.in/en/consentmgt/water-and-air-act', summary: 'Illustrative indexed amendment event for testing impact tracing across active consent pathways.', keywords: ['mpcb', 'consent', 'pollution', 'category', 'environment'], affectedRuleIds: ['mpcb-cte'], additionalDocuments: ['Updated pollution control proposal'], slaDays: [{ approvalId: 'mpcb-cte', days: 35 }] }];

export function calculateChangeImpact(project: ProjectData, input: Omit<OrchestrationInput, 'project'>, amendment: AmendmentEvent): ChangeImpactResult {
  const before = calculateOrchestration({ ...input, project });
  const affected = new Set(amendment.affectedRuleIds || []);
  const approvals = analyzeWithRulesEngine(project).approvals.map(item => ({ ...item, dependencies: amendment.dependenciesAdded?.filter(change => change.approvalId === item.id).reduce((deps, change) => deps.includes(change.dependsOn) ? deps : [...deps, change.dependsOn], [...item.dependencies]) || item.dependencies, timeline: amendment.slaDays?.find(change => change.approvalId === item.id) ? `${amendment.slaDays.find(change => change.approvalId === item.id)!.days} calendar days after complete submission` : item.timeline }));
  const after = calculateOrchestration({ ...input, project: { ...project }, approvalOverride: approvals });
  const impactedApprovals: ImpactItem[] = approvals.filter(item => affected.has(item.id) || amendment.keywords.some(keyword => `${item.title} ${item.agency} ${item.reason}`.toLowerCase().includes(keyword.toLowerCase()))).map(item => { const changes = ['Rule applicability requires review']; if (amendment.additionalDocuments?.length) changes.push(`Document set adds: ${amendment.additionalDocuments.join(', ')}`); if (amendment.slaDays?.some(change => change.approvalId === item.id)) changes.push('Published review target changed'); if (amendment.dependenciesAdded?.some(change => change.approvalId === item.id)) changes.push('Dependency chain changed'); return { approvalId: item.id, title: item.title, impact: changes.length > 2 ? 'high' : 'medium', changes, documents: [...item.documents, ...(amendment.additionalDocuments || [])], ragContext: `${amendment.title} may affect ${item.title}. Review ${amendment.sourceUrl} and revalidate the listed documents before continuing the route.` }; });
  const newDocuments = [...new Set(impactedApprovals.flatMap(item => item.documents).filter(document => amendment.additionalDocuments?.includes(document)))];
  return { amendment, before, after, impactedApprovals, newDocuments, prevalidationAction: newDocuments.length ? `Re-run Pre-Validation for ${newDocuments.join(', ')} before affected routes continue.` : 'No new document fields were identified; review impacted route evidence.', summary: impactedApprovals.length ? `${impactedApprovals.length} active approval route${impactedApprovals.length === 1 ? '' : 's'} require review after this amendment.` : 'No active approval route matched this amendment.' };
}
