'use client';

import { Background, Controls, Handle, MiniMap, Position, ReactFlow, type Edge, type Node } from '@xyflow/react';
import { AlertCircle, CheckCircle2, Clock3, Flame, Factory, GitBranch, LockKeyhole, Zap } from 'lucide-react';
import type { Approval } from '../../lib/arthix-rules';
import type { Application } from '../../lib/udyog';
import type { OrchestrationNodeStatus, OrchestrationResult } from '../../lib/dag-engine';

export type ArthixGraphStatus = Approval['status'] | Application['status'];
export type ArthixApprovalGraphProps = { approvals: Approval[]; statuses: Record<string, ArthixGraphStatus>; dag?: OrchestrationResult | null; onSelect: (approval: Approval) => void; onAskWhy?: (context: string) => void };
type GraphData = { label: string; agency: string; sla: string; status: OrchestrationNodeStatus; ragContext?: string; approval?: Approval; onSelect?: (approval: Approval) => void; onAskWhy?: (context: string) => void; synthetic?: boolean };
const labelStatus: Record<OrchestrationNodeStatus, string> = { startable: 'Startable', blocked: 'Blocked', 'in-progress': 'In progress', approved: 'Approved' };

function GraphNode({ data }: { data: GraphData }) {
  const Icon = data.synthetic ? (data.label.includes('readiness') ? CheckCircle2 : GitBranch) : data.approval?.serviceId === 'power' ? Zap : data.approval?.serviceId === 'fire' ? Flame : data.status === 'approved' ? CheckCircle2 : data.status === 'blocked' ? LockKeyhole : Factory;
  return <div className={`ax-graph-node ax-dag-node ax-dag-${data.status} ${data.synthetic ? 'ax-dag-synthetic' : ''}`}>
    <Handle type="target" position={Position.Left} className="ax-dag-handle" />
    <button type="button" className="ax-dag-card-button" onClick={() => data.approval && data.onSelect?.(data.approval)} aria-label={`Select ${data.label}`}>
      <span className="ax-node-icon"><Icon size={15}/></span><span className="ax-dag-copy"><strong>{data.label}</strong><small>{data.agency}</small><em><Clock3 size={10}/>{data.sla}</em></span><b className="ax-dag-status">{data.synthetic ? 'Gate' : labelStatus[data.status]}</b>{data.status === 'blocked' && data.ragContext && <span className="ax-dag-why" onClick={event => { event.stopPropagation(); data.onAskWhy?.(data.ragContext!); }}>Why?</span>}
    </button><Handle type="source" position={Position.Right} className="ax-dag-handle" />
  </div>;
}
const nodeTypes = { approval: GraphNode };

export function ArthixApprovalGraph({ approvals, statuses, dag, onSelect, onAskWhy }: ArthixApprovalGraphProps) {
  const fallback: OrchestrationResult = { generatedAt: new Date().toISOString(), rulesVersion: 'rules engine', assessmentId: 'fallback', validationGate: 'not-started', nodes: approvals.map(item => ({ id: item.id, title: item.title, agency: item.agency, estimatedDays: Math.max(1, Number(item.timeline.match(/\d+/)?.[0] || 15)), remainingDays: 15, deadline: null, escalated: false, status: (statuses[item.id] === 'approved' ? 'approved' : item.dependencies.length ? 'blocked' : 'startable') as OrchestrationNodeStatus, dependencies: item.dependencies, dependencyTypes: Object.fromEntries(item.dependencies.map(dep => [dep, 'hard'])), blockedReasons: [], ragContext: '', serviceId: item.serviceId, sourceUrl: item.officialUrl })), edges: [], criticalPath: [], criticalPathDays: 0, sequentialDays: 0, savingsDays: 0, parallelismPercent: 0, parallelTracks: [], targetDate: null };
  const graph = dag || fallback; const byId = new Map(approvals.map(item => [item.id, item])); const depth = (id: string, seen = new Set<string>()): number => { if (seen.has(id)) return 0; const node = graph.nodes.find(item => item.id === id); if (!node?.dependencies.length) return 0; const next = new Set(seen); next.add(id); return 1 + Math.max(...node.dependencies.map(dep => depth(dep, next))); }; const rows = new Map<number, number>();
  const nodes: Node<GraphData>[] = [{ id: 'entry', type: 'approval', position: { x: 20, y: 190 }, data: { label: 'Application received', agency: 'ARTHIX ORCHESTRATOR', sla: 'Validation gate', status: 'startable', synthetic: true, onAskWhy }, sourcePosition: Position.Right }, ...graph.nodes.map(node => { const level = depth(node.id); const row = rows.get(level) || 0; rows.set(level, row + 1); return { id: node.id, type: 'approval', position: { x: 280 + level * 300, y: 40 + row * 125 }, data: { label: node.title, agency: node.agency, sla: node.status === 'approved' ? 'Complete' : node.escalated ? 'Escalated' : `${node.remainingDays}d RTS target`, status: node.status, ragContext: node.ragContext, approval: byId.get(node.id), onSelect, onAskWhy }, sourcePosition: Position.Right, targetPosition: Position.Left }; }), { id: 'readiness', type: 'approval', position: { x: 940, y: 190 }, data: { label: 'Operational readiness', agency: 'ORCHESTRATOR GATE', sla: graph.validationGate === 'ready' ? 'Gate clear' : 'Validation required', status: graph.validationGate === 'ready' ? 'startable' : 'blocked', synthetic: true, onAskWhy }, targetPosition: Position.Left }];
  const edges: Edge[] = graph.edges.map(edge => ({ id: edge.id, source: edge.from, target: edge.to, animated: edge.critical, style: { stroke: edge.critical ? '#2563eb' : '#91a99d', strokeWidth: edge.critical ? 3 : 1.5 }, className: edge.critical ? 'ax-critical-edge' : undefined }));
  return <section className="ax-panel ax-graph-panel" aria-labelledby="ax-graph-title"><div className="ax-panel-heading"><div><span className="ax-kicker">ORCHESTRATION ENGINE / RULES + VALIDATION + RAG</span><h2 id="ax-graph-title">Approval dependency graph</h2><p>{graph.nodes.length ? 'Each connected route is calculated from rules, dossier readiness and application state.' : 'No approval routes match the current project profile.'}</p></div><span className="ax-live"><i/> Dynamic DAG</span></div><div className="ax-dag-summary"><span><GitBranch size={13}/> {graph.nodes.filter(node => node.status === 'startable').length} startable</span><span><LockKeyhole size={13}/> {graph.nodes.filter(node => node.status === 'blocked').length} blocked</span><span className="critical"><AlertCircle size={13}/> Critical path {graph.criticalPathDays}d</span><span className="saved">{graph.savingsDays}d saved vs sequential</span></div><div className="ax-flow-wrap"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView fitViewOptions={{ padding: .28, minZoom: .5 }} minZoom={.35} maxZoom={1.4} proOptions={{ hideAttribution: true }}><Background color="#d9e4df" gap={22} size={1}/><Controls showInteractive={false}/><MiniMap nodeColor={node => node.data?.status === 'blocked' ? '#c58b42' : node.data?.status === 'approved' ? '#31866f' : '#2563eb'}/></ReactFlow></div><div className="ax-branch-key"><span><i className="ax-key-power"/>Concurrent route</span><span><i className="ax-key-critical"/>Critical path</span><span><i className="ax-key-blocked"/>Waiting on prerequisite</span></div></section>;
}

